version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/" 
    schedule:
      interval: "weekly" 
    versioning-strategy: increase 
    allow:
      - dependency-type: "all" 
    ignore:
      - dependency-name: "django"
        versions: ["<4.0"] 
