# Generated by Django 4.2.24 on 2025-09-26 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0003_issue_assignee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='balise',
            field=models.CharField(choices=[('BUG', 'Bug'), ('FEATURE', 'Feature'), ('TASK', 'Task')], max_length=10),
        ),
        migrations.AlterField(
            model_name='issue',
            name='priority',
            field=models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'Hight')], max_length=10),
        ),
    ]
